options:
  metric_data_settling_interval:
    type: int
    default: 15
    description: |
      The minimum age (in seconds) of requested data points. When requesting
      recent aggregate metric data points, there is always a risk of seeing
      partial/incomplete results before metric values from all sources have
      been registered. The value to set for this field depends on the reporting
      frequency of monitoring agents, but as a general rule-of-thumb, this
      value can be set to be about 1.5 times the length of the
      reporting-interval for monitoring agents.
  scaling_cpu_max:
    type: int
    default: 80
    description: |
      CPU usage threshold at which the number of units should be scaled up.
  scaling_cpu_min:
    type: int
    default: 20
    description: |
      CPU threshold where the load is considered low enough to scale down the
      number of units.
  scaling_period_upscale:
    type: int
    default: 60
    description: |
      Number of seconds that the CPU usage needs to be higher than the
      threshold before scaling up.
  scaling_period_downscale:
    type: int
    default: 120
    description: |
      Number of seconds that the CPU usage needs to be lower than the threshold
      before scaling down.
  scaling_cooldown:
    type: int
    default: 300
    description: |
      Time (in seconds) before making another scaling decision from the time of
      the last up- or downscale. This is useful to prevent extra resizes due to
      slow teardowns or, in perticular, upstarts.
